### PR TITLE
Add whois permission and command to README.md

### PR DESCRIPTION
**Pull request by Brycey92**

### CODE REVIEW

**Comment by Eufranio** [comment]
This command is from MBDiscordLink, not from MagiBridge.

**Comment by Brycey92** [comment]
Ah, in that case should the registered permission be mbdiscordlink.whois?

**Comment by Asherslab** [comment]
No he's saying this is the wrong repo
it should be added to the MBDiscordLink repo

**Comment by Brycey92** [comment]
I know, but shouldn't the permission *itself* be `mbdiscordlink.whois` instead of starting with magibridge?

**Pull request closed without merging**
