### PR TITLE
Create message queue to condense command output

### PR DESCRIPTION
**Pull request by phase**
Running a command through the bot results in the output being split up
on every line.

Running `lp info` for example would give:

```[LP] Running LuckPerms v4.3.64 by Luck.```
```[LP] -  Platform: Sponge```
```[LP] -  Server Brand: SpongeVanilla```
```[LP] -  Server Version:```
```[LP] -  SpongeAPI: 7.1.0-70763aa8 - SpongeVanilla: 1.12.2-7.1.4```
```[LP] -  Storage:```
```[LP] -     Type: YAML```
```[LP] -  Messaging: None```
```[LP] -  Instance:```
```[LP] -     Static contexts: None```
```[LP] -     Online Players: 1 (3 unique)```
```[LP] -     Uptime: 9h 29m 13s```
```[LP] -     Local Data: 1 users, 5 groups, 0 tracks```

In Discord, these are all displayed as separate messages. This is ugly!
Now, the output of commands is sent to the message queue, which will
send all messages in one code block.

```
[LP] Running LuckPerms v4.3.64 by Luck.
[LP] -  Platform: Sponge
[LP] -  Server Brand: SpongeVanilla
[LP] -  Server Version:
[LP] -  SpongeAPI: 7.1.0-70763aa8 - SpongeVanilla: 1.12.2-7.1.4
[LP] -  Storage:
[LP] -     Type: YAML
[LP] -  Messaging: None
[LP] -  Instance:
[LP] -     Static contexts: None
[LP] -     Online Players: 1 (3 unique)
[LP] -     Uptime: 9h 29m 13s
[LP] -     Local Data: 1 users, 5 groups, 0 tracks
```

This looks much nicer in Discord.

### CODE REVIEW

**Comment by Eufranio** [comment]
I see you're sending the whole message at once. I'm sending message by message because of the 2000 characters limit that Discord has when sending messages, and commands sometimes have big responses that would easily bypass this limit, like pagination lists (they aren't "paginated" when sent to console, so it turns into a very big list if you have a lot of data).

**Comment by Asherslab** [comment]
well you could fix that issue by splitting the messages up every 200 characters or some similar solution

**Comment by phase** [comment]
I'll just make a buffer for the lines and send every chunk of 1990 characters,

**Comment by phase** [comment]
Should be good now :)

**Comment by Eufranio** [comment]
Thanks for this! 😃

**Pull request merged**
