### PR TITLE
Fix/Suggestion

### PR DESCRIPTION
**Pull request by poqdavid**
I made a fix for uchat channels and added topic-discord-channels="ID1,ID2" option

### CODE REVIEW

**Comment by Eufranio** [comment]
I have some concerns about this:
* You have duplicated logic on your topic updater code
* You're working with channels as longs rather than strings, why? 
* Since the topic channels are a list, why not store then on a list rather than a comma separated single string?

**Comment by poqdavid** [comment]
Well I meant to remove those then I forgot
And for the channels as long think of it as a way to make sure the id is in the correct format
for the topic channels wanted to make it as simple as possible

**Comment by Eufranio** [comment]
JDA throws an error for that, don't think it's needed.

**Comment by poqdavid** [comment]
true I just checked JDA's source it wasn't actually needed

**Comment by Eufranio** [comment]
Thanks!

**Pull request merged**
